### PR TITLE
build troubleshoot 2

### PR DESCRIPTION
**Pull request by danbjoseph**
This PR is a redo of #120 that preserves the Options and Flags format with a main list and the links out to a separate page for each one. Content additions are still added via the files in `arguments_edit` - the main change is that the `extract_odm_strings.py` script copies any of the added content into the individual argument page files instead of using the `.. include::` to reference the other file. By having all the content in one file, it enables translation for the Options and Flags content. 

The addition of `arguments_edit` to `exclude_patterns` in `conf.py` keeps that folder out of the build and avoids unnecessary pages that sit outside of the website navigation such as https://docs.opendronemap.org/arguments_edit/build-overviews/

I tested this and it appears to resolve the build failures.

### CODE REVIEW

**Comment by danbjoseph** [comment]
before:
Screen Shot 2021-11-12 at 4 51 48 PM
now (and this file can now be added to the translation workflow):
Screen Shot 2021-11-12 at 4 51 36 PM

**Comment by pierotofy** [comment]
Looks great, thanks @danbjoseph :pray:

**Comment by danbjoseph** [comment]
saw that the build failed again 😵‍💫

**Comment by pierotofy** [comment]
Strange, builds fine on my machine.

**Comment by pierotofy** [comment]
Does seem to be a problem with the `sw` language specifically (other languages build fine even on the github action machine).

**Pull request merged**
