### PR TITLE
Updated runtime parameters for 0.4

### PR DESCRIPTION
**Pull request by pierotofy**
As the title says.

### CODE REVIEW

**Comment by smathermather** [comment]
Should we remove ```--use-25dmesh```?

**Comment by smathermather** [comment]
Also, does ```--mesh-octree-depth``` now affect the 2.5d mesh?

**Comment by pierotofy** [comment]
` --use-25dmesh` is no longer used, so yes for removing it if it's referenced in other parts of the docs.

`--mesh-octree-depth` does affect the 2.5D mesh in the current `master`, but will not when the new 2.5D meshing program is approved and merged.

**Comment by smathermather** [comment]
Cool. And is this still true:
```
--use-3dmesh          Use a full 3D mesh to compute the orthophoto instead
                      of a 2.5D mesh. This option is a bit faster and
                      provides similar results in planar areas.
```

Is the 3D mesh still faster for orthophotos?

**Comment by pierotofy** [comment]
Yes (for planar areas).

**Comment by smathermather** [comment]
👍

**Pull request merged**
