### PR TITLE
Singularity tutorial

### PR DESCRIPTION
**Pull request by sbonaime**

### CODE REVIEW

**Comment by Saijin-Naib** [comment]
Love it!

However, I'm wondering if we might not be better off using less aggressive wording when talking about Docker. Instead, could you just talk about what Singularity does well without making a direct comparison? It might be less contentious.

So instead of something like "Docker does X badly", you could instead just state "Singularity is a containerization platform that does XYZ important things."

**Comment by pierotofy** [comment]
I think it looks good!

Thanks @sbonaime :pray: 

Feel free to make edits to improve the verbage @Saijin-Naib ?

**Comment by Saijin-Naib** [comment]
@sbonaime

Excellent first contribution, and thanks so much for providing another method to deploy and run WebODM 😎

**Comment by bravemaster3** [comment]
@sbonaime Thanks for the tutorial on singularity. When trying to use it, I cannot figure out what to change in the script and how to run it.
I guess this is because I am not used to singularity, but since I can't seem to find out how to use it, I thought of asking you directly.
Let's say I have my datasets organized like this:
/home/datasets/project/images
And I want ODM output to be in the project folder as we get for the docker odm documentation.

Here is the tutorial you wrote:


images_dir=/path_to_image_dir/
name=`basename $images_dir`
output_dir=/path_to_output_directories/$name
mkdir -p $output_dir

singularity run
--bind $images_dir:/$output_dir/code/images,\
--writable-tmpfs odm_latest.sif  \
--orthophoto-png --mesh-octree-depth 12 --ignore-gsd --dtm \
--smrf-threshold 0.4 --smrf-window 24 --dsm --pc-csv --pc-las --orthophoto-kmz \
--ignore-gsd  --matcher-type flann --feature-quality ultra --max-concurrency 16 \
--use-hybrid-bundle-adjustment --build-overviews --time --min-num-features 10000 \
--project-path $output_dir


Is /path_to_image_dir/ in my case "/home/datasets/project/"?
What should /path_to_output_directories/ be in my case ?
What else do I need to change?


Also, I don't seem to see the difference between the script for ODM and the script for ODM with gpu in the [documentation](https://docs.opendronemap.org/tutorials/#downloading-image).


Thanks !

**Comment by bravemaster3** [comment]
This works for me directly from the commandline:

singularity run --nv --bind /path_to_datasets:/datasets odm_gpu.sif --dsm --orthophoto-resolution 3.0 --project-path /datasets

Note that inside the images are in .../datasets/code/images

Thanks,

**Pull request merged**
