### PR TITLE
Update arguments.rst

### PR DESCRIPTION
**Pull request by gastgit**
Added --optimize-disk-space parameter from https://github.com/OpenDroneMap/ODM/blob/b698a087a046148c83f15945b0f54b09f807132e/opendm/config.py#L726

Also cleaned up the params page a bit

### CODE REVIEW

**Comment by smathermather** [comment]
Ahh, appreciate the cleanup as well. Merged.

**Comment by gastgit** [comment]
by the way, the version is 1.0.0 isn't it?
image

image

**Comment by smathermather** [comment]
Hmm, we should probably fix that too.

**Comment by gastgit** [comment]
There's probably more to moving from 0.9.1 to 1.0.0 than changing the number..;)
What are the changes 0.9.1 -> 1.0.0 that need to be added to docs?

**Pull request merged**
