### PR TITLE
add hidden fosstodon link for verification

### PR DESCRIPTION
**Pull request by danbjoseph**
https://docs.joinmastodon.org/user/profile/#verification

the above linked instructions say:
> the resolved page contains at least one a or link tag with a rel="me"

this PR results in this...
Screen Shot 2022-12-21 at 8 00 30 AM

do you want the link hidden? or visible as part of the page?

### CODE REVIEW

**Comment by pierotofy** [comment]
I think hidden works.

**Comment by danbjoseph** [comment]
then i think this should be good to go?

**Comment by danbjoseph** [comment]
@Saijin-Naib not sure who is admin-ing the Mastodon account. but if you remove, and add back in the docs link i hope it'll be verified now since 
`<a rel="me" style="visibility:hidden" aria-hidden="true"  href="https://fosstodon.org/@OpenDroneMap"></a>` 
is now present in the code for the https://docs.opendronemap.org/ landing page

**Comment by Saijin-Naib** [comment]
Dan, you absolute genius, you!

Thank you so much! I was wracking my brain on this and coming up short, haha.

How did you figure out how to do this? I'm going to follow up my Mastodon post asking for help with your answer.

**Comment by danbjoseph** [comment]
i've banged my head against the wall a lot during a number of different projects using sphinx in the past.
here's what i used: https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through
there may be better ways to do it.

**Pull request merged**
