### PR TITLE
Auto-generate options and flags section, version

### PR DESCRIPTION
**Pull request by pierotofy**
Automatically pulls the latest `config.py` from ODM and generates the `arguments.rst` page.

Also pulls the latest ODM version number on build.

image

### CODE REVIEW

**Comment by smathermather** [comment]
This is awesome. It's been on my todo list for a few months to organize the flags according to broader categories. Would there be a way to do that within this framework?

**Comment by pierotofy** [comment]
Currently, not.

I've been thinking about it also. I came up with two choices:

 - Add a new variable in the config options to specify to which group arguments belong to. 
 - Convention over configuration: if an option starts with `--<group>-config` (e.g. `--mesh-size` then it belongs to the `mesh` category). If an option does not specify a group, it belongs to a generic `system` or `generic` category.

The second will involve changing quite a bit of names, which might break workflows for folks (or add deprecation flags that support old names, but the list might become quite long).

**Comment by pierotofy** [comment]
Changing lots of option names all at once would fall in the scope of a major release. (3.x)

**Comment by smathermather** [comment]
> Changing lots of option names all at once would fall in the scope of a major release. (3.x)

Are you leaning a particular way? To me, it seems adding a variable is slightly more work upfront, but less brittle in the mid and long term.

**Comment by pierotofy** [comment]
Yeah I like convention over configuration, but for this case manually classifying options with extra params might give more flexibility and stability.

**Comment by smathermather** [comment]
Interesting: where did `--gps-accuracy` go? It doesn't show up in the built docs.

**Comment by pierotofy** [comment]
Huh, `--force-gps` is missing also.

**Comment by pierotofy** [comment]
I think it's because travis is broken.

**Comment by danbjoseph** [comment]
taking a look at this today

**Pull request merged**
