### PR TITLE
GitHub Actions, Arguments subpages

### PR DESCRIPTION
**Pull request by pierotofy**
:hand: this PR adds a GitHub action to publish changes to the docs on the `gh-pages` branch.

It also adds subpages to each task option, to allow people to expand the (currently missing) documentation on task options, which is frequently a large roadblock for people to understand how to tweak parameters.

### CODE REVIEW

**Comment by pierotofy** [comment]
image

**Comment by pierotofy** [comment]
The build action automatically regenerates the `rst` files in `source/arguments`, these should not be touched by humans for the English translation, but can be translated via transifex for other languages.

Additional information (typed by humans) can be added for each arguments in `source/arguments_edit`.

**Comment by danbjoseph** [comment]
closes #99. will take a look this afternoon or tomorrow.

**Comment by danbjoseph** [comment]
if there's no file yet for an argument in the `arguments_edit` folder the "help improve this page" the link will go to a 404. should the script generate a blank file for any argument that doesn't have a file in the `arguments_edit` folder? would that be possible? 
Screen Shot 2021-07-09 at 9 55 37 AM

**Comment by danbjoseph** [comment]
should there be something to tell the reader that the first line under the title is the possible options? also, an odd formatting glitch on lengthy lines of code.
Screen Shot 2021-07-09 at 9 59 58 AM

**Comment by Saijin-Naib** [comment]
> should there be something to tell the reader that the first line under the title is the possible options? also, an odd formatting glitch on lengthy lines of code.
> Screen Shot 2021-07-09 at 9 59 58 AM

I've been thinking that I wanted to sub-class each parameter with things like Type (Toggle, argument, etc), Domain (possible values), Default, example syntax, Description, then preview/images.

**Comment by danbjoseph** [comment]
@Saijin-Naib do you think you could mock something up, if even just a pen&ink wireframe? does this require just some minor adjustments to the current templating or something more significant (that is, something for this PR or something more significant later)?

**Comment by Saijin-Naib** [comment]
> @Saijin-Naib do you think you could mock something up, if even just a pen&ink wireframe? does this require just some minor adjustments to the current templating or something more significant (that is, something for this PR or something more significant later)?

I _think_ at this point it should all be eminently doable under the current structure Piero set up. Really, I think it's just up to me and how little rST-fu I know currently.

I'll try to push a template/example here for you to look at. I'm almost certain that as I start doing this and more, I'll have to make adjustments, but for the time being what I proposed above seems to make sense in my head.

**Comment by pierotofy** [comment]
Thanks for the review Dan, I'll take care of the points you mentioned within the next few days.

**Comment by pierotofy** [comment]
Ok, I've added a label to the options, fixed the out-of-page render issue and added default pages for each parameter (this is done automatically via the script). :pray: 

Let me know if further changes are warranted.

**Review by danbjoseph — APPROVED** [review]

**Pull request merged**
