### PR TITLE
CNAME for docs.opendronemap.org

### PR DESCRIPTION
**Pull request by danbjoseph**
@smathermather can you direct docs.opendronemap.org for this?
https://help.github.com/articles/setting-up-a-custom-subdomain/

### CODE REVIEW

**Comment by smathermather** [comment]
No problem. Out of the office this week, but I can take care of this early next week.

**Comment by smathermather** [comment]
Should be done!

**Comment by danbjoseph** [comment]
thanks @smathermather !
http://docs.opendronemap.org/

**Comment by smathermather** [comment]
My pleasure. Thanks for your help with this!

**Pull request merged**
