### PR TITLE
adding arabic

### PR DESCRIPTION
**Pull request by danbjoseph**
the html for other languages still has `lang="en"` in the page metadata...
and i think the arabic html is supposed to have a `dir="rtl"` tag on the page?

Screen Shot 2020-08-05 at 9 00 54 PM

### CODE REVIEW

**Comment by smathermather** [comment]
Should be `ar` according to https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language

Edit: re-reading -- Right to left. Hmm, I should think so.

**Comment by danbjoseph** [comment]
so i tried building with the default theme (`alabaster`) and the `lang` metadata tag is set correctly. possibly something wrong with `html_theme = 'sphinx_rtd_theme'`
 Screen Shot 2020-08-06 at 9 01 49 AM

**Comment by danbjoseph** [comment]
upgraded the theme and edited `conf.py` and now the `lang` tag is generated correctly. will have to check with someone if the arabic pages display correctly.

**Comment by danbjoseph** [comment]
Screen Shot 2020-08-06 at 9 12 45 AM
Screen Shot 2020-08-06 at 9 12 38 AM
Screen Shot 2020-08-06 at 9 12 30 AM

**Comment by smathermather** [comment]
> upgraded the theme and edited `conf.py` and now the `lang` tag is generated correctly. will have to check with someone if the arabic pages display correctly.

Yup. I don't know conventions or frankly the script at all, but it's there:
image

**Comment by smathermather** [comment]
I better switch my browser back though:
image

**Pull request merged**
