### PR TITLE
build troubleshoot

### PR DESCRIPTION
**Pull request by danbjoseph**
I was trying to troubleshoot the recent build failure after a push from @Saijin-Naib (I've seen the error before and I don't think it's related to his changes). I haven't yet solved why a variation of the following error shows up for sw, te, and fil languages. The error also seems to come and go and I can't seem to consistently replicate it.
```
/Users/danbjoseph/Documents/GitHub/OpenDroneMap/docs/source/arguments.rst:: WARNING: rST localisation for language "sw" not found.
```
I'm wondering if it has something to do with the `arguments.rst` file, and the `arguments/` folder of files, and each of those files pulling in the text from a file in the `arguments_edit` folder. That structure of things also challenges the translation process. Each file that is to be translated needs to be added into the [`./tx/config`](https://github.com/OpenDroneMap/docs/blob/publish/.tx/config) file. And each file becomes a "resource" in Transifex. There are a large number of files given that there are potentially 2 for every option - which would complicate keeping the `config` file updated and also negatively impact translators' experience on Transifex.

This PR changes so that we push everything (both the details from ODM and the user additions to files in `arguments_edit`) into the single `source/arguments.rst` file instead of having the main arguments page with individual pages for each argument that repeat the info + add some if there are user additions in the arguments_edit folder.

This should cleanly enable translation of all the content for **Options and Flags**. The only downside I can see is that it's a lot on one page, but I think adding some spacing a thick horizontal rule between each option helps. We can adjust the styling but possibly something like this:

Screen Shot 2021-11-11 at 6 39 20 PM

The addition of `arguments_edit` to `exclude_patterns` in `conf.py` keeps that folder out of the build and avoids unnecessary pages that sit outside of the website navigation such as https://docs.opendronemap.org/arguments_edit/build-overviews/ 

I'm hoping that this PR also fixes the build error but to fully test I need to push/pull from Transifex - which involves creating changes on that platform that might be messy to reverse. So I want to get acceptance or rejection of this overall approach first before proceeding with the testing.

Happy to answer any questions and looking forward to hearing what you think.

### CODE REVIEW

**Comment by Saijin-Naib** [comment]
Oof... I don't really like them being all on one page. It makes linking directly really problematic, and as you pointed out, kind of visually noisy.

I think having the ToC with levels is much nicer to use and navigate.

I want to really expand each option, and I just don't see it being usable at all on one huge flat page.

**Comment by danbjoseph** [comment]
Each section still has an accessible permalink for the heading:
Screen Shot 2021-11-11 at 9 06 23 PM

What about if I looked into an expand/collapse details like this example from the [ODK docs](https://docs.getodk.org/central-install-digital-ocean/#adding-external-storage)?

### Collapsed:
Screen Shot 2021-11-11 at 9 07 48 PM

### Expanded:
Screen Shot 2021-11-11 at 9 07 52 PM

**Comment by Saijin-Naib** [comment]
I'm still not super fond of a single page for all of that content. It just feels messy and not at all like there are logical divisions between the subject matter. Collapsing is visually cleaner, but I still think it lacks the benefits of hierarchical organization. There's a logical flow to that that can help provide context and imply relationships.

I plan on expanding each section with examples and Further Reading once I get everything more fully fleshed out.
Loading that in one go is going to be brutal. I really do think the flow of the ToC is an important way to keep the document navigable, and having pages/subpages ensures that the amount of content fetched at once remains more reasonable.

**Comment by pierotofy** [comment]
Mm, it's strange that transifex cannot be setup using the current layout (I'm also for keeping the pages separately).

> which would complicate keeping the config file updated 

Agreed, this should not be done by hand. Needs to be automated. Can it? Happy to help here if needed.

**Comment by danbjoseph** [comment]
I will work on a solution that preserves the separate pages. That makes sense with the added context of how much you plan on building out these pages.

**Comment by Saijin-Naib** [comment]
I'm sorry for making this a pain (and for somehow kicking the hornets nest when I published two weeks ago 😬) and I truly appreciate you taking the time to help build this out so nicely.

**Pull request closed without merging**
