### PR TITLE
--auto-boundary

### PR DESCRIPTION
**Pull request by Saijin-Naib**
This begins filling out the description of the auto-boundary option. Further profiling and comparisons will follow in the future.

### CODE REVIEW

**Comment by pierotofy** [comment]
Nice!

**Comment by Saijin-Naib** [comment]
I hope it builds right! I'm still getting failures of CI in my fork and I have no idea why 😬

**Comment by pierotofy** [comment]
It looks like it built fine.

**Comment by danbjoseph** [comment]
the github actions config might not work in a fork. also it's not setup to test branches i don't think, but @Saijin-Naib  you need/want increased permissions so that you can work on a branch on the main repo?

**Comment by Saijin-Naib** [comment]
I'm not sure if that's right yet. I'm still breaking stuff, haha.

**Pull request merged**
