### PR TITLE
[WIP] add back in Swahili

### PR DESCRIPTION
**Pull request by danbjoseph**
need to manually copy/paste completed Swahili translations into Transifex as we are using that platform now

this uses the translations by @khastylez from #48 but pulls them from Transifex rather than editing the text files directly

### CODE REVIEW

**Comment by danbjoseph** [comment]
i think i've now copy-pasted everything over into Transifex

**Comment by smathermather** [comment]
Ugh. Missed the [WIP]. Reverted the merge. Sorry for the noise.

**Comment by danbjoseph** [comment]
would have been fine, just missing review. will open a new PR.

**Comment by smathermather** [comment]
Sorry about that. I like to start my week with a little quick review on Sunday night, but often I am not that smart on Sunday night... . New pull is merged.

**Pull request merged**
