### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by johngithens**
I have not discovered how to make additional change suggestions after my first two "Propose changes" actions. 

There appear to be two stages for "Create pull request".

So, I have stopped making contributions until there is feedback from a core project team member.

I just tapped the dropdown arrow for "Create pull request" on this page, saw the two items in the drop down, however I did not detect any response when tapping one in the list.  When I tapped the initial "Create pull request" button, there was a response. (These subtle UI "features" should be explained to any novice user of github, in the WebODM instructions for "Simply...".)

### CODE REVIEW

**Comment by Saijin-Naib** [comment]
Welcome! Thanks for the PR!

About the style guide: Do you believe our documentation follows it, or should?

More specifically for this PR, it is mentioned twice (once in Quick and once in Pro). Do you think it might be worth mentioning once before/after instead of repeating?

**Comment by johngithens** [comment]
heh, at first I thought: "Why am I being thanked for some Public Relations
thing?"

Overall, the ODM docs which I have read so far...   are not too bad, other
than frequent misspellings, missing punctuation marks, and other indicators
that an author was writing more for people they work with, rather than for
people who are beginning to experience a novel (to them) subculture of the
world with its special contexts, terms and definitions.

That said, I know that it is difficult for people who have deep knowledge
of, and experience in a topic to remember what it was like when they had
less knowledge.

I don't know if the current Docs adhere to every assertion in the Style
Guide. I am not convinced that complete adherence is necessary. However,
some effort to remove the "personality" of expressions by some author(s)
may be helpful to readers.

I will admit to being mildly irritated when I see a sentence intended to
explain a technical topic which starts with "Simply..." or "Basically...".
Technical documentation is not the place to sell or convince the reader,
only to explain.

That said, I'm not interested in playing an English Police role. I was only
looking for the easiest way to correct the more obvious (to me) errors or
sequencing that could confuse readers.

Overall, I think that the Style Guide should be referenced early on the
page (not repeated). I stopped working on my suggestions when I encountered
too many obstacles to being a Contributor.

John

**Comment by Saijin-Naib** [comment]
Totally fair.

I too had quite a bit of a learning curve starting out! I also still break stuff so I've got plenty more to learn 🤣

We are maintaining and expanding the documentation, so I appreciate your feedback and the work you started on!

I have some ideas for how things might be made easier, but I need to refine the workflow before I write it up.

Yes, qualifiers can be tough in documentation. I appreciate you highlighting this. It's a pretty common speech pattern thing, so it sneaks into writing easily.

**Comment by johngithens** [comment]
Sounds good. Looking forward to a better workflow in README.md. I'm happy
to test it.

**Review by pierotofy — APPROVED** [review]

**Comment by pierotofy** [comment]
Thanks for the improved instructions!

**Pull request merged**
