### PR TITLE
Update build-overviews.rst

### PR DESCRIPTION
**Pull request by Saijin-Naib**
This contains the core of what I'd like to add for each argument going forward.

### CODE REVIEW

**Review by pierotofy — APPROVED** [review]
Looks great!

When rendered on a browser the impact ASCII characters don't render quite as nicely as with the text editor, perhaps a value of `L` (low) `M` (medium) or `H` (high) would be easier to read (see screenshot).

image

Also perhaps the Parameter domain part is unnecessary for booleans since it's implied that it's either true (on) or false (off). 

Love the QGIS screenshots.

**Comment by danbjoseph** [comment]
yeah, this looks good but the visualization of the impact is not intuitive to me.

**Comment by Saijin-Naib** [comment]
Thanks for the feedback!

I'd like to keep the Domain for all values for consistency, but in looking at your Screenshot, I think I might be best putting the parameter options in code blocks so the syntax isn't lost to becoming a ligature. It also looks like it rendered slightly differently here... I'll have to play with this more.
Screenshot from 2021-07-31 01-02-08

Dan, would you think a colorblind friendly color ramp with the symbols would help?

My limited local testing seems to indicate that the Impact graph is generally intuitively understood, so I'd like to try and improve it rather than drop it.

**Comment by pierotofy** [comment]
How about something like:

image

**Comment by Saijin-Naib** [comment]
image
Does this read better to everyone?

I think with colors this will read really quickly/easily, especially with the addition of the legend text.

**Comment by pierotofy** [comment]
Love the dots. Yes it reads a lot better. :+1:

**Comment by pierotofy** [comment]
Thanks @Saijin-Naib !

**Pull request merged**
