### PR TITLE
Mermaid flowchart with options

### PR DESCRIPTION
**Pull request by sbonaime**
mermaid_flowchart in the doc

- [x] Check errors in the flowchart 
- [x] Modify the flowchart  style to nicely fit in a webpage
- [x] add links to doc (if possible) for each option in the flowchart 
- [x] maybe move the flowchart in a better place

Capture d’écran 2024-06-27 à 13 28 44

### CODE REVIEW

**Comment by Saijin-Naib** [comment]
Looks great!

Why was transifex-client bumped back down to 0.12.5 from 0.14.4? Is there some incompatibility with mermaid?

**Comment by sbonaime** [comment]
@Saijin-Naib I had I think this issue
https://github.com/transifex/transifex-client/issues/332
I revert to 0.12.5

**Comment by sbonaime** [comment]
Also update virtualenv to venv as virtualenv
-  needs to be installed for Python 3.3
-  Python 3.3 is EOL since 2017...

https://www.dataquest.io/blog/a-complete-guide-to-python-virtual-environments/
NOTE There are two tools for setting up virtual environments, virtualenv and venv, that we can use almost interchangeably. virtualenv supports older Python versions and needs to be installed using the pip command. In contrast, venv is only used with Python 3.3 or higher and is included in the Python standard library, requiring no installation.

**Comment by sbonaime** [comment]
Any idea to move the flowchart somewhere else ?

**Comment by Saijin-Naib** [comment]
> Any idea to move the flowchart somewhere else ?

I do not have any concrete ideas, no.

What are you concerned about with your current location for it?

**Comment by sbonaime** [comment]
I put it at this place without really thinking about it.

**Comment by sbonaime** [comment]
Then, can you merge this PR ? 
Thanks !

**Comment by smathermather** [comment]
Sorry for the delay: travel slowed down my review.

Maybe move to after options and flags and call it done for now.

Since @Saijin-Naib is working on a re-org of the docs this summer, I think it'll be fine there until the re-org is complete.

**Comment by Saijin-Naib** [comment]
I wanted to test it in my fork to make sure CI doesnt get mad at any changes first, but yeah, I will merge and we can go from there.

**Comment by sbonaime** [comment]
I just move the flowchart after "options and flags".

**Comment by Saijin-Naib** [comment]
CI go brrrrr. 

Thanks so much for this. This is so incredibly cool!

**Pull request merged**
